/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;
import model.Appointment;
import javax.swing.JOptionPane;

/**
 *
 * @author D
 */
public class AppointmentDetails extends javax.swing.JFrame {
    
    private AppointmentDAO appointmentDAO;

    /**
     * Creates new form NewAppoinment
     */
    public AppointmentDetails() {
        initComponents();
        
        // Create DAO object
        appointmentDAO = new AppointmentDAO();

        // Window settings
        setTitle("Appointment Details");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        // Make result area read-only
        txtARappNo.setEditable(false);

        // Press Enter inside appointment number field to search
        txtAppNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSearch();
            }
        });
        
        // Search button
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSearch();
            }
        });
    }

    /**
     * Search appointment by appointment number.
     */
    private void onSearch() {

        String appointmentNo = txtAppNo2.getText().trim();
        txtARappNo.setText("");

        // Check if appointment number was entered
        if (appointmentNo.isEmpty()) {

    JOptionPane.showMessageDialog(
        this,
        "Please enter an appointment number.",
        "Missing Information",
        JOptionPane.WARNING_MESSAGE
    );

    txtAppNo2.requestFocus();
    return;
}

// Validate appointment number format
if (!appointmentNo.matches("[A-Za-z0-9-]+")) {

    JOptionPane.showMessageDialog(
        this,
        "Appointment number can contain only letters, numbers, and hyphens.",
        "Invalid Appointment Number",
        JOptionPane.WARNING_MESSAGE
    );

    txtAppNo2.requestFocus();
    return;
}

        // Search appointment in database
        try {

    Appointment appointment =
            appointmentDAO.findByAppointmentNo(appointmentNo);

    if (appointment != null) {

        StringBuilder sb = new StringBuilder();

        sb.append("========================================\n");
        sb.append("        APPOINTMENT DETAILS\n");
        sb.append("========================================\n\n");

        sb.append("Appointment No   : ")
          .append(appointment.getAppointmentNo())
          .append("\n\n");

        sb.append("Patient Name     : ")
          .append(appointment.getPatientName())
          .append("\n\n");

        sb.append("Address          : ")
          .append(appointment.getAddress())
          .append("\n\n");

        sb.append("Contact Number   : ")
          .append(appointment.getContactNumber())
          .append("\n\n");

        sb.append("Dentist Name     : ")
          .append(appointment.getDentistName())
          .append("\n\n");

        sb.append("Treatment Type   : ")
          .append(appointment.getTreatmentType())
          .append("\n\n");

        sb.append("Appointment Date : ")
          .append(appointment.getAppointmentDate())
          .append("\n\n");

        sb.append("Appointment Time : ")
          .append(appointment.getAppointmentTime())
          .append("\n\n");

        sb.append("========================================");

        txtARappNo.setText(sb.toString());

    } else {

        txtARappNo.setText("");

        JOptionPane.showMessageDialog(
            this,
            "No appointment found with number: " + appointmentNo,
            "Not Found",
            JOptionPane.WARNING_MESSAGE
        );

        txtAppNo2.requestFocus();
    }

} catch (Exception ex) {

    txtARappNo.setText("");

    JOptionPane.showMessageDialog(
        this,
        "Unable to search for the appointment.\n"
        + "Please check the database connection and try again.",
        "Search Error",
        JOptionPane.ERROR_MESSAGE
    );

    txtAppNo2.requestFocus();
}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblAppNo1 = new javax.swing.JLabel();
        txtAppNo2 = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtARappNo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(0, 153, 153));
        lblSearch.setText("Search Appointment Details");
        getContentPane().add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 353, 52));

        lblAppNo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAppNo1.setText("Appointment No:");
        getContentPane().add(lblAppNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, 28));

        txtAppNo2.setBackground(new java.awt.Color(244, 244, 255));
        getContentPane().add(txtAppNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 208, 35));

        btnSearch2.setBackground(new java.awt.Color(217, 250, 250));
        btnSearch2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch2.setText("Search");
        getContentPane().add(btnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, -1));

        txtARappNo.setBackground(new java.awt.Color(244, 244, 255));
        txtARappNo.setColumns(20);
        txtARappNo.setRows(5);
        jScrollPane1.setViewportView(txtARappNo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 640, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-540, -330, 1470, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppNo1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextArea txtARappNo;
    private javax.swing.JTextField txtAppNo2;
    // End of variables declaration//GEN-END:variables
}
