/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;
import model.Appointment;
import model.Bill;
import service.EmailService;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;

/**
 *
 * @author D
 */
public class BillForm extends javax.swing.JFrame {
    
    // Consultation fee applied to every bill
    private static final double CONSULTATION_FEE = 500.0;

    private AppointmentDAO appointmentDAO;
    private Bill currentBill;


    /**
     * Creates new form newbill
     */
    public BillForm() {
        initComponents();

    appointmentDAO = new AppointmentDAO();

    setTitle("Calculate and Print Bill");
    setLocationRelativeTo(null);
    setDefaultCloseOperation(
        javax.swing.WindowConstants.DISPOSE_ON_CLOSE
    );
    setResizable(false);

    txtArBill.setEditable(false);

    txtArBill.setFont(
        new java.awt.Font(
            "Monospaced",
            java.awt.Font.PLAIN,
            13
        )
    );

    // Press Enter to generate bill
    txtAppNo2.addActionListener(e -> onGenerateBill());

    // Generate Bill button
    btnGenBill.addActionListener(e -> onGenerateBill());

    // Print button
    btnPrint.addActionListener(e -> onPrint());

    // Close button
    btnClose3.addActionListener(e -> dispose());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrintBill = new javax.swing.JLabel();
        lblAppNo3 = new javax.swing.JLabel();
        txtAppNo2 = new javax.swing.JTextField();
        btnGenBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArBill = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnClose3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrintBill.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblPrintBill.setForeground(new java.awt.Color(102, 153, 255));
        lblPrintBill.setText("Print Bill");
        getContentPane().add(lblPrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 180, 58));

        lblAppNo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAppNo3.setText("Appointment No:");
        getContentPane().add(lblAppNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));
        getContentPane().add(txtAppNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 244, 37));

        btnGenBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGenBill.setText("Generate Bill");
        getContentPane().add(btnGenBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 140, 40));

        txtArBill.setColumns(20);
        txtArBill.setRows(5);
        jScrollPane1.setViewportView(txtArBill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 639, 390));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnClose3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClose3.setText("Close");
        getContentPane().add(btnClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 840, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    
    private void onGenerateBill() {

    String appointmentNo = txtAppNo2.getText().trim();

    if (appointmentNo.isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Please enter an appointment number.",
            "Missing Information",
            JOptionPane.WARNING_MESSAGE
        );

        txtAppNo2.requestFocus();
        return;
    }

    Appointment appointment =
        appointmentDAO.findByAppointmentNo(appointmentNo);

    if (appointment == null) {

        txtArBill.setText("");
        currentBill = null;

        JOptionPane.showMessageDialog(
            this,
            "No appointment found with number: " + appointmentNo,
            "Not Found",
            JOptionPane.WARNING_MESSAGE
        );

        txtAppNo2.requestFocus();
        return;
    }

    double treatmentCost =
        appointmentDAO.getTreatmentCost(
            appointment.getTreatmentType()
        );

// Validate treatment cost
if (treatmentCost <= 0) {

    txtArBill.setText("");
    currentBill = null;

    JOptionPane.showMessageDialog(
        this,
        "Unable to retrieve the treatment cost.",
        "Billing Error",
        JOptionPane.ERROR_MESSAGE
    );

    return;
}

currentBill = new Bill(
        appointment.getAppointmentNo(),
        appointment.getPatientName(),
        appointment.getTreatmentType(),
        CONSULTATION_FEE,
        treatmentCost
    );

    boolean billSaved = appointmentDAO.saveBill(
        currentBill.getAppointmentNo(),
        currentBill.getConsultationFee(),
        currentBill.getTreatmentCost(),
        currentBill.getTotalAmount()
);

if (!billSaved) {

    JOptionPane.showMessageDialog(
            this,
            "The bill could not be saved to the database.",
            "Billing Error",
            JOptionPane.ERROR_MESSAGE
    );

} else {

    // Get patient email from Appointment object
    String patientEmail = appointment.getEmail();

    // Check whether an email address exists
    if (patientEmail != null && !patientEmail.trim().isEmpty()) {

        boolean emailSent = EmailService.sendAppointmentEmail(
                patientEmail,
                appointment.getPatientName(),
                appointment.getAppointmentNo(),
                ""
        );

        if (emailSent) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill saved successfully and email sent to:\n"
                    + patientEmail,
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill was saved successfully, but the email could not be sent.\n"
                    + "Please check the NetBeans Output window.",
                    "Email Error",
                    JOptionPane.WARNING_MESSAGE
            );
        }

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Bill was saved successfully, but this patient does not have an email address.",
                "Email Not Available",
                JOptionPane.WARNING_MESSAGE
        );
    }
}

    StringBuilder sb = new StringBuilder();

    sb.append("========================================\n");
    sb.append("        SUNRISE DENTAL CLINIC\n");
    sb.append("             Patient Bill\n");
    sb.append("========================================\n\n");

    sb.append(String.format(
        "Appointment No : %s%n",
        currentBill.getAppointmentNo()
    ));

    sb.append(String.format(
        "Patient Name   : %s%n",
        currentBill.getPatientName()
    ));

    sb.append(String.format(
        "Dentist Name   : %s%n",
        appointment.getDentistName()
    ));

    sb.append(String.format(
        "Treatment Type : %s%n",
        currentBill.getTreatmentType()
    ));

    sb.append(String.format(
        "Appointment    : %s %s%n",
        appointment.getAppointmentDate(),
        appointment.getAppointmentTime()
    ));

    sb.append("\n----------------------------------------\n");

    sb.append(String.format(
        "Consultation Fee : Rs. %10.2f%n",
        currentBill.getConsultationFee()
    ));

    sb.append(String.format(
        "Treatment Cost   : Rs. %10.2f%n",
        currentBill.getTreatmentCost()
    ));

    sb.append("----------------------------------------\n");

    sb.append(String.format(
        "TOTAL AMOUNT     : Rs. %10.2f%n",
        currentBill.getTotalAmount()
    ));

    sb.append("========================================\n");
    sb.append("      Thank you for visiting us!\n");
    sb.append("========================================\n");

    txtArBill.setText(sb.toString());
}


private void onPrint() {

    if (currentBill == null) {

        JOptionPane.showMessageDialog(
            this,
            "Please generate a bill first.",
            "No Bill",
            JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        boolean printed = txtArBill.print();

        if (!printed) {

            JOptionPane.showMessageDialog(
                this,
                "Print job was cancelled.",
                "Print Cancelled",
                JOptionPane.INFORMATION_MESSAGE
            );
        }

    } catch (PrinterException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error printing bill: " + e.getMessage(),
            "Print Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose3;
    private javax.swing.JButton btnGenBill;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppNo3;
    private javax.swing.JLabel lblPrintBill;
    private javax.swing.JTextField txtAppNo2;
    private javax.swing.JTextArea txtArBill;
    // End of variables declaration//GEN-END:variables
}
