/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author D
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form NewHelp
     */
    public Help() {
        initComponents();
        
        // Set window properties
        setTitle("Help - How to Use the System");
        setLocationRelativeTo(null);
        setResizable(false);

        // Make the help text read-only
        txtArHelp.setEditable(false);
        txtArHelp.setLineWrap(true);
        txtArHelp.setWrapStyleWord(true);

        // Add help information
        txtArHelp.setText(
                "1. LOGIN\n"
                + "   Enter the username and password provided by the clinic\n"
                + "   administrator, then click 'Login'. Only authorized staff\n"
                + "   can access the system.\n\n"

                + "2. REGISTER NEW APPOINTMENT\n"
                + "   From the Main Menu, select 'Register New Appointment'.\n"
                + "   The appointment number is generated automatically.\n"
                + "   Fill in the patient name, address, contact number,\n"
                + "   dentist name, treatment type, date (yyyy-MM-dd) and\n"
                + "   time (HH:mm), then click 'Save Appointment'.\n\n"

                + "3. DISPLAY APPOINTMENT DETAILS\n"
                + "   Select 'Display Appointment Details' from the Main Menu.\n"
                + "   Enter the appointment number and click 'Search' to view\n"
                + "   the full patient and appointment information.\n\n"

                + "4. CALCULATE AND PRINT BILL\n"
                + "   Select 'Calculate and Print Bill' from the Main Menu.\n"
                + "   Enter the appointment number and click 'Generate Bill'\n"
                + "   to calculate the consultation fee, treatment cost and\n"
                + "   total amount. Click 'Print Bill' to send the receipt\n"
                + "   to your printer.\n\n"

                + "5. EXIT SYSTEM\n"
                + "   Select 'Exit System' from the Main Menu and confirm to\n"
                + "   safely close the application.\n\n"

                + "For further assistance, please contact the system\n"
                + "administrator."
        );

        // Close button action
        btnClose4.addActionListener(e -> dispose());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSunriseUserGuide = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArHelp = new javax.swing.JTextArea();
        btnClose4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSunriseUserGuide.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblSunriseUserGuide.setForeground(new java.awt.Color(255, 153, 153));
        lblSunriseUserGuide.setText("Sunrise Dental Clinic - User Guide");
        getContentPane().add(lblSunriseUserGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 627, 60));

        txtArHelp.setColumns(20);
        txtArHelp.setRows(5);
        jScrollPane1.setViewportView(txtArHelp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 760, 450));

        btnClose4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClose4.setText("Close");
        getContentPane().add(btnClose4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 546, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel1.setMinimumSize(new java.awt.Dimension(830, 700));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 970, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSunriseUserGuide;
    private javax.swing.JTextArea txtArHelp;
    // End of variables declaration//GEN-END:variables
}
