/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author D
 */
public class ManageUsers extends javax.swing.JFrame {
    
    private User currentUser;
    private UserDAO userDAO;

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers(User user) {
        initComponents();

    currentUser = user;
    userDAO = new UserDAO();

    setTitle("Manage Users");
    setLocationRelativeTo(null);
    setDefaultCloseOperation(
            javax.swing.WindowConstants.DISPOSE_ON_CLOSE
    );
    setResizable(false);

    // Role combo box
    jComboBoxRole.removeAllItems();
    jComboBoxRole.addItem("ADMIN");
    jComboBoxRole.addItem("DOCTOR");
    jComboBoxRole.addItem("RECEPTIONIST");

    // Load usernames from database
    loadUsernames();


    }
    /**
 * Load all usernames from the database into the combo box.
 */
private void loadUsernames() {

    jComboBoxUser.removeAllItems();

    List<String> usernames = userDAO.getAllUsernames();

    for (String username : usernames) {
        jComboBoxUser.addItem(username);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtUser2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JTextField();
        btnRegister2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxUser = new javax.swing.JComboBox<>();
        btnBack2 = new javax.swing.JButton();
        btnDelete3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Add / Remove Users");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 262, 52));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("New User Role");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 117, 32));

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 152, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("User Name : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 108, -1));
        getContentPane().add(txtUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 152, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Password: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 117, -1));

        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 152, -1));

        btnRegister2.setBackground(new java.awt.Color(204, 0, 204));
        btnRegister2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister2.setText("Register");
        btnRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 86, -1));

        jComboBoxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 128, -1));

        btnBack2.setBackground(new java.awt.Color(255, 204, 204));
        btnBack2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 270, -1, -1));

        btnDelete3.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete3.setText("Delete User");
        btnDelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Full Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 20));
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 150, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserPage.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 980, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void btnRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister2ActionPerformed
    // Get values from form
    String role = jComboBoxRole.getSelectedItem().toString().trim();
    String fullName = txtFullName.getText().trim();
    String username = txtUser2.getText().trim();
    String password = txtPass2.getText().trim();

    // Validate full name
    if (fullName.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter the full name.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE
        );

        txtFullName.requestFocus();
        return;
    }

    // Validate username
    if (username.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a username.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE
        );

        txtUser2.requestFocus();
        return;
    }

    // Validate password
    if (password.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a password.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE
        );

        txtPass2.requestFocus();
        return;
    }

    // Check whether username already exists
    if (userDAO.usernameExists(username)) {

        JOptionPane.showMessageDialog(
                this,
                "The username '" + username
                + "' already exists.\n"
                + "Please choose another username.",
                "Username Already Exists",
                JOptionPane.WARNING_MESSAGE
        );

        txtUser2.requestFocus();
        return;
    }

    // Register user
    boolean success = userDAO.registerUser(
            username,
            password,
            fullName,
            role
    );

    if (success) {

        JOptionPane.showMessageDialog(
                this,
                "User registered successfully!\n\n"
                + "Full Name: " + fullName + "\n"
                + "Username: " + username + "\n"
                + "Role: " + role,
                "Registration Successful",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Clear fields
        txtFullName.setText("");
        txtUser2.setText("");
        txtPass2.setText("");

        // Refresh username combo box
        loadUsernames();

        txtFullName.requestFocus();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to register the user.\n"
                + "Please check the database connection.",
                "Registration Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnRegister2ActionPerformed

    private void btnDelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete3ActionPerformed
        // Check whether combo box has a username
    if (jComboBoxUser.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(
                this,
                "There are no users available to delete.",
                "No Users",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String username =
            jComboBoxUser.getSelectedItem().toString();

    // Confirm deletion
    int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete user '"
            + username + "'?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (choice != JOptionPane.YES_OPTION) {
        return;
    }

    // Delete user
    boolean deleted =
            userDAO.deleteUser(username);

    if (deleted) {

        JOptionPane.showMessageDialog(
                this,
                "User '" + username
                + "' has been deleted successfully.",
                "Delete Successful",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Refresh combo box
        loadUsernames();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "The user could not be deleted.\n"
                + "The user may no longer exist.",
                "Delete Failed",
                JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnDelete3ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        new MenuForm(currentUser).setVisible(true);
this.dispose(); 
    }//GEN-LAST:event_btnBack2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnDelete3;
    private javax.swing.JButton btnRegister2;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JComboBox<String> jComboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPass2;
    private javax.swing.JTextField txtUser2;
    // End of variables declaration//GEN-END:variables
}
