/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author D
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form NewForm
     */
    public MenuForm(User user) {
        initComponents();
        
        setTitle("Sunrise Dental Clinic - Main Menu");
        setSize(450, 420);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        btnBillCal = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        Dashboardlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName1.setForeground(new java.awt.Color(51, 0, 0));
        lblName1.setText("Sunrise Dental Clinic");
        getContentPane().add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 400, 55));

        lblName2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(153, 0, 0));
        lblName2.setText("Logged In As: System Administrator");
        getContentPane().add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 360, 30));

        btnDisplay.setBackground(new java.awt.Color(204, 204, 255));
        btnDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDisplay.setText("2.Display Appoinment Details");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 250, 40));

        btnBillCal.setBackground(new java.awt.Color(204, 204, 255));
        btnBillCal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBillCal.setText("3.Calculate and Print Bill");
        btnBillCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillCalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBillCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 250, 30));

        btnHelp.setBackground(new java.awt.Color(204, 204, 255));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHelp.setText("4.Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 110, -1));

        btnRegister.setBackground(new java.awt.Color(204, 204, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setText("1.Register New Appoinment");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 207, 250, 30));

        btnExit1.setBackground(new java.awt.Color(204, 204, 255));
        btnExit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit1.setText("5.Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 100, -1));

        Dashboardlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        Dashboardlbl.setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().add(Dashboardlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        btnDisplay.addActionListener(e -> new AppointmentDetails().setVisible(true));
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnBillCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillCalActionPerformed
        btnBillCal.addActionListener(e -> new BillForm().setVisible(true));
    }//GEN-LAST:event_btnBillCalActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        btnHelp.addActionListener(e -> new Help().setVisible(true));
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        btnRegister.addActionListener(e -> new RegisterAppointment().setVisible(true));
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to exit the system?",
                "Confirm Exit", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        btnExit1.addActionListener(e -> onExit());
    }//GEN-LAST:event_btnExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private User user;
            public void run() {
                new MenuForm(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboardlbl;
    private javax.swing.JButton btnBillCal;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    // End of variables declaration//GEN-END:variables

    private void onExit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
