/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;
import java.sql.Date;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Appointment;

/**
 *
 * @author D
 */
public class RegisterAppointment extends javax.swing.JFrame {

    private AppointmentDAO appointmentDAO;

    /**
     * Creates new form NewRegister
     */
    public RegisterAppointment() {
        initComponents();

     appointmentDAO = new AppointmentDAO();

        // Generate appointment number
        txtappNo.setText(appointmentDAO.generateNextAppointmentNo());
        txtappNo.setEditable(false);

        // Address settings
        txtAddre.setLineWrap(true);
        txtAddre.setWrapStyleWord(true);

        // Load treatment types from database
        // Treatment types
        String[] treatments = {
                "Braces Consultation",
                "Consultation",
                "Denture Fitting",
                "Extraction",
                "Filling",
                "Root Canal",
                "Scaling",
                "Whitening"
            };

        jcbTreat.setModel(
            new javax.swing.DefaultComboBoxModel<>(treatments)
        );

        setTitle("Register New Appointment");
        setSize(800, 560);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblregiii = new javax.swing.JLabel();
        lblPatien = new javax.swing.JLabel();
        lblappNo = new javax.swing.JLabel();
        lblAddre = new javax.swing.JLabel();
        lblCon = new javax.swing.JLabel();
        txtappNo = new javax.swing.JTextField();
        txtPateint = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        lblTreat = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        lblDenti = new javax.swing.JLabel();
        jcbTreat = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDenti = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnSaveApp = new javax.swing.JButton();
        btnCloseApp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddre = new javax.swing.JTextArea();
        lblBackgroReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblregiii.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblregiii.setForeground(new java.awt.Color(0, 102, 102));
        lblregiii.setText("Register New Appoinment");
        getContentPane().add(lblregiii, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 331, 48));

        lblPatien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPatien.setText("Patient Name:");
        getContentPane().add(lblPatien, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 123, 147, -1));

        lblappNo.setBackground(new java.awt.Color(255, 255, 255));
        lblappNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblappNo.setText("Appoinment No:");
        getContentPane().add(lblappNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 90, 160, -1));

        lblAddre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddre.setText("Address:");
        getContentPane().add(lblAddre, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 159, 93, -1));

        lblCon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCon.setText("Contact Number:");
        getContentPane().add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 243, 181, -1));

        txtappNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtappNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtappNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtappNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 240, 22));

        txtPateint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPateint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPateintActionPerformed(evt);
            }
        });
        getContentPane().add(txtPateint, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 230, -1));

        txtTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 382, 227, -1));

        lblTreat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTreat.setText("Treatment Type:");
        getContentPane().add(lblTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 315, 181, -1));

        txtConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContaActionPerformed(evt);
            }
        });
        getContentPane().add(txtConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 244, 227, -1));

        lblDenti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDenti.setText("Dentist Name:");
        getContentPane().add(lblDenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 279, 149, -1));

        jcbTreat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbTreat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTreatActionPerformed(evt);
            }
        });
        getContentPane().add(jcbTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 316, 227, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setText("Date (yyyy-mm-dd)");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 351, -1, -1));

        txtDenti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtDenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 280, 227, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setText("Time (hh:mm)");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 381, -1, -1));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 352, 227, -1));

        btnSaveApp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveApp.setForeground(new java.awt.Color(102, 0, 102));
        btnSaveApp.setText("Save Appoinment");
        btnSaveApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAppActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 201, -1, -1));

        btnCloseApp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCloseApp.setForeground(new java.awt.Color(102, 0, 102));
        btnCloseApp.setText("Close");
        btnCloseApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAppActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 265, -1, -1));

        txtAddre.setColumns(20);
        txtAddre.setRows(5);
        jScrollPane2.setViewportView(txtAddre);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 230, 70));

        lblBackgroReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register (2).png"))); // NOI18N
        getContentPane().add(lblBackgroReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-720, -350, 1520, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContaActionPerformed

    private void jcbTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTreatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTreatActionPerformed

    private void txtappNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtappNoActionPerformed
       
    }//GEN-LAST:event_txtappNoActionPerformed

    private void txtPateintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPateintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPateintActionPerformed

    private void btnSaveAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAppActionPerformed
        onSave();
    }//GEN-LAST:event_btnSaveAppActionPerformed

    private void btnCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAppActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseAppActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    /**
     * Save appointment to database.
     */
    private void onSave() {

        String appointmentNo = txtappNo.getText().trim();
        String patientName = txtPateint.getText().trim();
        String address = txtAddre.getText().trim();
        String contact = txtConta.getText().trim();
        String dentist = txtDenti.getText().trim();

        String treatment = "";

        if (jcbTreat.getSelectedItem() != null) {
            treatment = jcbTreat.getSelectedItem().toString().trim();
        }

        String dateStr = txtDate.getText().trim();
        String timeStr = txtTime.getText().trim();

        // Validate required fields
        if (patientName.isEmpty()
        || address.isEmpty()
        || contact.isEmpty()
        || dentist.isEmpty()
        || treatment.isEmpty()
        || dateStr.isEmpty()
        || timeStr.isEmpty()) {

            JOptionPane.showMessageDialog(
                this,
                "Please fill in all required fields.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        Date sqlDate;
        Time sqlTime;

        // Validate date and time
        try {

            SimpleDateFormat dateFormat =
                    new SimpleDateFormat("yyyy-MM-dd");

            dateFormat.setLenient(false);

            java.util.Date parsedDate =
                    dateFormat.parse(dateStr);

            sqlDate = new Date(parsedDate.getTime());

            SimpleDateFormat timeFormat =
                    new SimpleDateFormat("HH:mm");

            timeFormat.setLenient(false);

            java.util.Date parsedTime =
                    timeFormat.parse(timeStr);

            sqlTime = new Time(parsedTime.getTime());

        } catch (ParseException ex) {

            JOptionPane.showMessageDialog(
                this,
                "Invalid date or time format.\n\n"
                + "Use:\n"
                + "Date: yyyy-MM-dd\n"
                + "Time: HH:mm",
                "Format Error",
                JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Create Appointment object
        Appointment appointment = new Appointment(
                appointmentNo,
                patientName,
                address,
                contact,
                dentist,
                treatment,
                sqlDate,
                sqlTime
        );

        // Insert appointment into database
        boolean success =
                appointmentDAO.insertAppointment(appointment);

        if (success) {

            JOptionPane.showMessageDialog(
                this,
                "Appointment registered successfully!\n"
                + "Appointment No: " + appointmentNo,
                "Success",
                JOptionPane.INFORMATION_MESSAGE
            );

            clearForm();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Failed to register appointment.\n"
                + "Please try again.",
                "Database Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Clear form after successful registration.
     */
    private void clearForm() {

        txtappNo.setText(
            appointmentDAO.generateNextAppointmentNo()
        );

        txtPateint.setText("");
        txtAddre.setText("");
        txtConta.setText("");
        txtDenti.setText("");
        txtDate.setText("");
        txtTime.setText("");

        if (jcbTreat.getItemCount() > 0) {
            jcbTreat.setSelectedIndex(0);
        }

        txtPateint.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()
            ).log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()
            ).log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()
            ).log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()
            ).log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new RegisterAppointment().setVisible(true);
                }
            }
        );
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseApp;
    private javax.swing.JButton btnSaveApp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbTreat;
    private javax.swing.JLabel lblAddre;
    private javax.swing.JLabel lblBackgroReg;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDenti;
    private javax.swing.JLabel lblPatien;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTreat;
    private javax.swing.JLabel lblappNo;
    private javax.swing.JLabel lblregiii;
    private javax.swing.JTextArea txtAddre;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDenti;
    private javax.swing.JTextField txtPateint;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtappNo;
    // End of variables declaration//GEN-END:variables
}
